spring.application.name=ParcelDelivery
# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/parcel_delivery
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

#HashId
tracking.hashids.salt=uX9$mK2@pL5#nQ8
tracking.hashids.min-length=10