spring.application.name=ParcelDelivery
# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/parcel_delivery
spring.datasource.username=postgres
spring.datasource.password=admin
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
#HashId
tracking.hashids.salt=uX9$mK2@pL5#nQ8
tracking.hashids.min-length=10
#System var
packing.scheduler.interval-ms=15000
packing.scheduler.initial-delay-ms=15000

#Logging
logging.level.org.dzianisbova.parceldelivery=INFO
logging.level.org.dzianisbova.parceldelivery.assignment=DEBUG